-- #741: Bulk / Cut を独立したシーズンとして管理する基盤
--
-- 方針:
--   - 1 season = 1 phase (Cut / Bulk)
--   - user ごとの active season は最大 1 件
--   - season 期間は user 内で重複不可（境界日は両端を含む）
--   - daily_logs.season_id は nullable。期間外ログを誤帰属させない
--   - career_logs は後続 migration で owner / season を backfill して owner-scoped にする

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS seasons (
  id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name                       TEXT        NOT NULL,
  phase                      TEXT        NOT NULL,
  start_date                 DATE        NOT NULL,
  start_weight               NUMERIC     NOT NULL,
  target_date                DATE        NOT NULL,
  target_weight              NUMERIC,
  status                     TEXT        NOT NULL DEFAULT 'active',
  end_date                   DATE,
  end_weight                 NUMERIC,
  monthly_plan_start_month   TEXT,
  monthly_plan_start_weight  NUMERIC,
  monthly_plan_overrides     JSONB       NOT NULL DEFAULT '[]'::JSONB,
  created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT seasons_id_user_id_key UNIQUE (id, user_id),
  CONSTRAINT seasons_user_name_start_key UNIQUE (user_id, name, start_date),
  CONSTRAINT seasons_name_not_blank CHECK (BTRIM(name) <> ''),
  CONSTRAINT seasons_phase_check CHECK (phase IN ('Cut', 'Bulk')),
  CONSTRAINT seasons_status_check CHECK (status IN ('active', 'completed')),
  CONSTRAINT seasons_start_weight_check CHECK (start_weight > 0 AND start_weight <= 300),
  CONSTRAINT seasons_target_weight_check CHECK (
    target_weight IS NULL OR (target_weight >= 20 AND target_weight <= 200)
  ),
  CONSTRAINT seasons_end_weight_check CHECK (
    end_weight IS NULL OR (end_weight > 0 AND end_weight <= 300)
  ),
  CONSTRAINT seasons_monthly_plan_start_weight_check CHECK (
    monthly_plan_start_weight IS NULL
    OR (monthly_plan_start_weight > 0 AND monthly_plan_start_weight <= 300)
  ),
  CONSTRAINT seasons_target_date_check CHECK (target_date >= start_date),
  CONSTRAINT seasons_state_dates_check CHECK (
    (status = 'active' AND end_date IS NULL AND end_weight IS NULL)
    OR
    (status = 'completed' AND end_date IS NOT NULL AND end_date >= start_date)
  ),
  -- 新規 active season は目標体重必須。既存 career_logs には目標体重がないため、
  -- migrated completed season だけは NULL を許容する。
  CONSTRAINT seasons_active_target_weight_check CHECK (
    status = 'completed' OR target_weight IS NOT NULL
  ),
  CONSTRAINT seasons_monthly_plan_start_month_check CHECK (
    monthly_plan_start_month IS NULL
    OR monthly_plan_start_month ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
  ),
  CONSTRAINT seasons_monthly_plan_overrides_check CHECK (
    JSONB_TYPEOF(monthly_plan_overrides) = 'array'
  )
);

COMMENT ON TABLE seasons IS
  'Bulk / Cut を独立管理するシーズン。1 user につき active は最大 1 件。';
COMMENT ON COLUMN seasons.phase IS 'Cut または Bulk。進行中 season の phase は直接切り替えない。';
COMMENT ON COLUMN seasons.start_date IS 'シーズン所属期間の開始日。この日から新 season に所属する。';
COMMENT ON COLUMN seasons.end_date IS '終了済み season の最終所属日。active は NULL。';
COMMENT ON COLUMN seasons.target_weight IS
  '目標体重。active は必須。legacy career_logs 由来 completed season は不明なため NULL 可。';
COMMENT ON COLUMN seasons.monthly_plan_overrides IS
  'シーズン単位の月次目標 override JSON 配列。#743 で UI / snapshot を接続する。';

CREATE UNIQUE INDEX IF NOT EXISTS seasons_one_active_per_user_idx
  ON seasons(user_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS seasons_user_start_date_idx
  ON seasons(user_id, start_date);

-- daterange は両端を含む。active season は infinity までを占有するため、
-- active より後の season を作るには先に旧 season を completed にする必要がある。
DO $$
BEGIN
  ALTER TABLE seasons
    ADD CONSTRAINT seasons_user_period_excl
    EXCLUDE USING GIST (
      user_id WITH =,
      DATERANGE(start_date, COALESCE(end_date, 'infinity'::DATE), '[]') WITH &&
    );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE OR REPLACE FUNCTION set_seasons_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS seasons_set_updated_at ON seasons;
CREATE TRIGGER seasons_set_updated_at
BEFORE UPDATE ON seasons
FOR EACH ROW EXECUTE FUNCTION set_seasons_updated_at();

ALTER TABLE seasons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated owner can select seasons" ON seasons;
DROP POLICY IF EXISTS "authenticated owner can insert seasons" ON seasons;
DROP POLICY IF EXISTS "authenticated owner can update seasons" ON seasons;
DROP POLICY IF EXISTS "authenticated owner can delete seasons" ON seasons;

CREATE POLICY "authenticated owner can select seasons"
  ON seasons FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE POLICY "authenticated owner can insert seasons"
  ON seasons FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());
CREATE POLICY "authenticated owner can update seasons"
  ON seasons FOR UPDATE TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY "authenticated owner can delete seasons"
  ON seasons FOR DELETE TO authenticated USING (user_id = auth.uid());

-- ── daily_logs の season 所属 ────────────────────────────────────────────────

ALTER TABLE daily_logs
  ADD COLUMN IF NOT EXISTS season_id BIGINT;

DO $$
BEGIN
  ALTER TABLE daily_logs
    ADD CONSTRAINT daily_logs_season_owner_fkey
    FOREIGN KEY (season_id, user_id)
    REFERENCES seasons(id, user_id)
    ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE INDEX IF NOT EXISTS daily_logs_user_season_date_idx
  ON daily_logs(user_id, season_id, log_date);

COMMENT ON COLUMN daily_logs.season_id IS
  'log_date が所属する season。どの期間にも属さない場合は NULL。';

CREATE OR REPLACE FUNCTION resolve_season_id(
  p_user_id UUID,
  p_log_date DATE
) RETURNS BIGINT
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
  SELECT s.id
  FROM public.seasons AS s
  WHERE s.user_id = p_user_id
    AND s.start_date <= p_log_date
    AND (s.end_date IS NULL OR s.end_date >= p_log_date)
  ORDER BY s.start_date DESC
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION resolve_season_id(UUID, DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION resolve_season_id(UUID, DATE) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION assign_daily_log_season_id()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF NEW.user_id IS NULL THEN
    NEW.season_id = NULL;
  ELSE
    NEW.season_id = public.resolve_season_id(NEW.user_id, NEW.log_date);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS daily_logs_assign_season_id ON daily_logs;
CREATE TRIGGER daily_logs_assign_season_id
BEFORE INSERT OR UPDATE OF user_id, log_date ON daily_logs
FOR EACH ROW EXECUTE FUNCTION assign_daily_log_season_id();

-- ── legacy career_logs の owner / season 接続準備 ────────────────────────────

ALTER TABLE career_logs
  ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS season_id BIGINT;

DO $$
BEGIN
  ALTER TABLE career_logs
    ADD CONSTRAINT career_logs_season_owner_fkey
    FOREIGN KEY (season_id, user_id)
    REFERENCES seasons(id, user_id)
    ON DELETE RESTRICT;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

COMMENT ON COLUMN career_logs.user_id IS 'Owner user id。#741 migration で既存行を一意な owner へ backfill。';
COMMENT ON COLUMN career_logs.season_id IS '対応する completed Cut season。';
